### ISSUE TITLE
Can not set uplink and downlink bandwidth limit for Hysteria2 inbound

### ISSUE THREAD

**Issue by yhd12138** [alireza0/s-ui#92] opened 2024-03-30 03:54 UTC
The number in the textbox always changes to zero.

**Comment by agczsz** [comment] 2024-04-04 00:17
the problem is quite serious

**Comment by alireza0** [comment] 2024-04-15 17:58
Thank you for reporting this bug. I will fix it soon.

**Comment by alireza0** [comment] 2024-04-16 13:19
It is fixed now!
You can build it manually or wait for next release

**Closed by alireza0** 2024-04-16 13:19 UTC
Labels: bug, to deploy
